import { sudo } from "./parsers/types";

export function getProxmoxBackupGuardCommand(): string {
  return [
    "# Block rebooting Proxmox VE while backup tasks are running.",
    "if ! command -v pveversion >/dev/null 2>&1 && ! command -v pvesh >/dev/null 2>&1; then",
    "  exit 0",
    "fi",
    "",
    "if ! command -v pvesh >/dev/null 2>&1; then",
    "  echo \"Reboot blocked: Proxmox detected but pvesh is unavailable.\"",
    "  exit 1",
    "fi",
    "",
    "tasks=$(",
    `  ${sudo("pvesh get /cluster/tasks --output-format json")} 2>&1`,
    ")",
    "status=$?",
    "if [ \"$status\" -ne 0 ]; then",
    "  echo \"Reboot blocked: could not verify Proxmox backup activity.\"",
    "  printf '%s\\n' \"$tasks\"",
    "  exit 1",
    "fi",
    "",
    "running_backup=$(",
    "  printf '%s\\n' \"$tasks\" | perl -MJSON::PP -e '",
    "    local $/;",
    "    my $decoded = decode_json(<STDIN>);",
    "    my $tasks = ref($decoded) eq \"HASH\" ? ($decoded->{data} // []) : $decoded;",
    "    die \"unexpected task response\\n\" unless ref($tasks) eq \"ARRAY\";",
    "    for my $task (@$tasks) {",
    "      next unless ref($task) eq \"HASH\";",
    "      next unless ($task->{type} // \"\") eq \"vzdump\";",
    "      if (exists $task->{pid} || ($task->{status} // \"\") eq \"running\") {",
    "        print \"yes\\n\";",
    "        last;",
    "      }",
    "    }",
    "  ' 2>&1",
    ")",
    "status=$?",
    "if [ \"$status\" -ne 0 ]; then",
    "  echo \"Reboot blocked: could not verify Proxmox backup activity.\"",
    "  printf '%s\\n' \"$running_backup\"",
    "  printf '%s\\n' \"$tasks\"",
    "  exit 1",
    "fi",
    "",
    "if [ \"$running_backup\" = \"yes\" ]; then",
    "  echo \"Reboot blocked: Proxmox backup task is running.\"",
    "  printf '%s\\n' \"$tasks\"",
    "  exit 1",
    "fi",
  ].join("\n");
}

export function getRebootCommand(): string {
  return [
    "# Reboot the remote system using sudo when the current user is not root.",
    sudo("reboot"),
  ].join("\n");
}
